# Linguistic Markers for Dementia
Automatic language assessment methods help clinicians detect linguistic markers associated with dementia. Here, we describe different linguistic markers such as incoherent speech, tangentiality and grammatical error, lexical retrieval difficulties, auditory comprehension difficulties, grammatical and spelling failures and present python scripts to extercat them.

## Incoherent speech 


A text with incoherent speech has not a relevant order between sentences. To measure rambling speech in a text, we can define a score based on the similarity score between sentences of the text. Thus, we first review different methods to measure text similritoes and various techniques to compute pairwise similarities between two sentences.

### Text Similrit Measures

A good review of text similarit measuure has been provided in [1]. 

1.  Jaccard Similarity

2.  Cosine Similarity

2.1. Cosine Similarity using Spacyx
2.2. Cosine Similarity using Scipy



### Jaccard Similarity


In [ ]:
def Jaccard_Similarity(text_1, text_2): 
    
    # List the unique words in a document
    words_list1 = set(text_1.lower().split()) 
    words_list2 = set(text_2.lower().split())
    
    # Find the intersection of words list of doc1 & doc2
    intersection = words_list1.intersection(words_list2)

    # Find the union of words list of doc1 & doc2
    union = words_list1.union(words_list2)
        
    # Calculate Jaccard similarity score 
    # using length of intersection set divided by length of union set
    return float(len(intersection)) / len(union)
text_1 = "Two children, a girl  reaching for the cookie jar."
text_2 = "Mother is She has a dish in your hand or is. "

Jaccard_Similarity(text_1,text_2)

0.05263157894736842

### Cosine Similarity



In [ ]:

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text_1 = "Two children, a girl  reaching for the cookie jar."
text_2 = "Mother is She has a dish in your hand or is. "
words_list_1 = set(text_1.lower().split()) 
words_list_2 = set(text_2.lower().split()) 
# tokenization
#words_list_1 = word_tokenize(text_1) 
#words_list_2 = word_tokenize(text_2)
  
# sw contains the list of stopwords
#sw = stopwords.words('english') 
l1 =[];l2 =[]
  
# remove stop words from the string
words_set_1 = {w for w in words_list_1} 
words_set_2 = {w for w in words_list_2}
  
# form a set containing keywords of both strings 
rvector = words_set_1.union(words_set_2) 
for w in rvector:
    if w in words_set_1: l1.append(1) # create a vector
    else: l1.append(0)
    if w in words_set_2: l2.append(1)
    else: l2.append(0)
c = 0
  
# cosine formula 
for i in range(len(rvector)):
        c+= l1[i]*l2[i]
cosine = c / float((sum(l1)*sum(l2))**0.5)
print("similarity: ", cosine)

similarity:  0.10050378152592121


In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc1 = nlp(u'Two children, a girl  reaching for the cookie jar.') 
doc2 = nlp(u'Mother is She has a dish in your hand or is.')
print (doc1.similarity(doc2)) 

0.4966613486251336


/usr/lib/python3.7/runpy.py:193: ModelsWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  "__main__", mod_spec)


In [ ]:
!pip install tensorflow
!pip install tensorflow_hub

In [ ]:
def heatmap(x_labels, y_labels, values):
    fig, ax = plt.subplots()
    im = ax.imshow(values)

    # We want to show all ticks...
    ax.set_xticks(np.arange(len(x_labels)))
    ax.set_yticks(np.arange(len(y_labels)))
    # ... and label them with the respective list entries
    ax.set_xticklabels(x_labels)
    ax.set_yticklabels(y_labels)

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right", fontsize=10,
         rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    for i in range(len(y_labels)):
        for j in range(len(x_labels)):
            text = ax.text(j, i, "%.2f"%values[i, j],
                           ha="center", va="center", color="w", 
fontsize=6)

    fig.tight_layout()
    plt.show()

In [ ]:
import tensorflow_hub as hub
import tensorflow as tf
import numpy as np
module_url = "https://tfhub.dev/google/universal-sentence-encoder/1?tf-hub-format=compressed"
# Import the Universal Sentence Encoder's TF Hub module
embed = hub.Module(module_url)

# sample text
messages = [
# Smartphones
"My phone is not good.",
"Your cellphone looks great.",

# Weather
"Will it snow tomorrow?",
"Recently a lot of hurricanes have hit the US",

# Food and health
"An apple a day, keeps the doctors away",
"Eating strawberries is healthy",
]

similarity_input_placeholder = tf.placeholder(tf.string, shape=(None))
similarity_message_encodings = embed(similarity_input_placeholder)
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    session.run(tf.tables_initializer())
    message_embeddings_ = session.run(similarity_message_encodings, feed_dict={similarity_input_placeholder: messages})

    corr = np.inner(message_embeddings_, message_embeddings_)
    print(corr)
    heatmap(messages, messages, corr)

RuntimeError: ignored

In [ ]:
def heatmap(x_labels, y_labels, values):
    fig, ax = plt.subplots()
    im = ax.imshow(values)

    # We want to show all ticks...
    ax.set_xticks(np.arange(len(x_labels)))
    ax.set_yticks(np.arange(len(y_labels)))
    # ... and label them with the respective list entries
    ax.set_xticklabels(x_labels)
    ax.set_yticklabels(y_labels)

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right", fontsize=10,
         rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    for i in range(len(y_labels)):
        for j in range(len(x_labels)):
            text = ax.text(j, i, "%.2f"%values[i, j],
                           ha="center", va="center", color="w", 
fontsize=6)

    fig.tight_layout()
    plt.show()

## Word Embedding
Word Embedding, a technique in the language modeling domain, is utilized to map words or phrases that can be mapped to vectors of real numbers with several dimensions using word embedding. 
Different methods have been proposed as word embeddings. Here we review practices that have been used in the language of patients with dementia. 

1. Bag-Of-Words

2. Doc2vec 

3. Doc2vecC

4. TF-IDF

5. Word2Vec




### Bag-Of-Words

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
 
vector = CountVectorizer()
#
# Create sample set of documents
#
docs = np.array([
'Two children, a girl  reaching for the cookie jar. ',
'Mother is She has a dish in your hand or is.',
'They have a garden',
'There is a window with curtains', 
'The window was open. ',
'She is wearing a dress and apron. ',
'Cookie jar coverage open']
)
#
# Fit the bag-of-words model
#
bag = vector.fit_transform(docs)
#
# Get unique words / tokens found in all the documents. The unique words / tokens represents
# the features
#
print(vector.get_feature_names())
#
# Associate the indices with each unique word
#
print(vector.vocabulary_)
#
# Print the numerical feature vector
#
print(bag.toarray())

['and', 'apron', 'children', 'cookie', 'coverage', 'curtains', 'dish', 'dress', 'for', 'garden', 'girl', 'hand', 'has', 'have', 'in', 'is', 'jar', 'mother', 'open', 'or', 'reaching', 'she', 'the', 'there', 'they', 'two', 'was', 'wearing', 'window', 'with', 'your']
{'two': 25, 'children': 2, 'girl': 10, 'reaching': 20, 'for': 8, 'the': 22, 'cookie': 3, 'jar': 16, 'mother': 17, 'is': 15, 'she': 21, 'has': 12, 'dish': 6, 'in': 14, 'your': 30, 'hand': 11, 'or': 19, 'they': 24, 'have': 13, 'garden': 9, 'there': 23, 'window': 28, 'with': 29, 'curtains': 5, 'was': 26, 'open': 18, 'wearing': 27, 'dress': 7, 'and': 0, 'apron': 1, 'coverage': 4}
[[0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 2 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0]
 [1 1 0 0 0 0 0 1 0 0 0 0 0 0 0

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


### Doc2vec

## Tangentiality

## Grammatical error
To find out the grammatical errors in a text that a patient has provided with Alzheimer's disease dementia, you can use TextBlob Library
[TextBlob](https://pypi.org/project/textblob/0.9.0/), which is a text processing library. 

### Introduction to TextBlob


###*Installing TextBlob*

In [ ]:
!pip install textblob==0.9.0

In [ ]:
from textblob import TextBlob
text=TextBlob('I havv a bad spelling')
##For Spelling Correction, we can use correct() method to correct spell
#textc=text.correct()
#print(textc)
print(text)
print(text.correct())

I havv a bad spelling



## Introduction to Gingerit
Using gingerit,you can correcting spelling and grammar mistakes based on the context of complete entences.

### *Installing Gingerit*

In [ ]:
! pip install gingerit


     |████████████████████████████████| 63 kB 989 kB/s 
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.


In [ ]:
from gingerit.gingerit import GingerIt
import pandas as pd
text = "Two chldren, a grl reching for the cooki jar"
parser = GingerIt()
parser.parse(text)
b=parser.parse(text)
#pd.set_option('max_colwidth', 520)
corrected_df = parser.parse(text)
corrected_df = pd.DataFrame(corrected_df)
corrected_df

text  ...                                                                                                               corrections
0  Two chldren, a grl reching for the cooki jar  ...                {'start': 35, 'text': 'cooki', 'correct': 'cookie', 'definition': 'any of various small flat sweet cakes'}
1  Two chldren, a grl reching for the cooki jar  ...  {'start': 19, 'text': 'reching', 'correct': 'reaching', 'definition': 'the act of physically reaching or thrusting out'}
2  Two chldren, a grl reching for the cooki jar  ...                                            {'start': 15, 'text': 'grl', 'correct': 'girl', 'definition': 'a young woman'}
3  Two chldren, a grl reching for the cooki jar  ...                      {'start': 4, 'text': 'chldren', 'correct': 'children', 'definition': 'a young person of either sex'}

[4 rows x 3 columns]

# Refrences

[1]. [Overview of Text Similarity Metrics in Python](https://towardsdatascience.com/overview-of-text-similarity-metrics-3397c4601f50)