# Linguistic Markers for Dementia
Automatic language assessment methods help clinicians detect linguistic markers associated with dementia. Here, we describe different linguistic markers such as incoherent speech, tangentiality and grammatical error, lexical retrieval difficulties, auditory comprehension difficulties, grammatical and spelling failures and present python scripts to extercat them.

## Incoherent speech 


A text with incoherent speech has not a relevant order between sentences. To measure rambling speech in a text, we can define a score based on the similarity score between sentences of the text. Thus, we first review different methods to measure text similritoes and various techniques to compute pairwise similarities between two sentences.

### Text Similrit Measures

A good review of text similarit measuure has been provided in [1]. 

1.  Jaccard Similarity

2.  Cosine Similarity

2.1. Cosine Similarity using Spacyx
2.2. Cosine Similarity using Scipy



### Jaccard Similarity


In [ ]:
def Jaccard_Similarity(text_1, text_2): 
    
    # List the unique words in a document
    words_list1 = set(text_1.lower().split()) 
    words_list2 = set(text_2.lower().split())
    
    # Find the intersection of words list of doc1 & doc2
    intersection = words_list1.intersection(words_list2)

    # Find the union of words list of doc1 & doc2
    union = words_list1.union(words_list2)
        
    # Calculate Jaccard similarity score 
    # using length of intersection set divided by length of union set
    return float(len(intersection)) / len(union)
text_1 = "Two children, a girl  reaching for the cookie jar."
text_2 = "Mother is She has a dish in your hand or is. "

Jaccard_Similarity(text_1,text_2)

0.05263157894736842

### Cosine Similarity



In [ ]:

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text_1 = "Two children, a girl  reaching for the cookie jar."
text_2 = "Mother is She has a dish in your hand or is. "
words_list_1 = set(text_1.lower().split()) 
words_list_2 = set(text_2.lower().split()) 
# tokenization
#words_list_1 = word_tokenize(text_1) 
#words_list_2 = word_tokenize(text_2)
  
# sw contains the list of stopwords
#sw = stopwords.words('english') 
l1 =[];l2 =[]
  
# remove stop words from the string
words_set_1 = {w for w in words_list_1} 
words_set_2 = {w for w in words_list_2}
  
# form a set containing keywords of both strings 
rvector = words_set_1.union(words_set_2) 
for w in rvector:
    if w in words_set_1: l1.append(1) # create a vector
    else: l1.append(0)
    if w in words_set_2: l2.append(1)
    else: l2.append(0)
c = 0
  
# cosine formula 
for i in range(len(rvector)):
        c+= l1[i]*l2[i]
cosine = c / float((sum(l1)*sum(l2))**0.5)
print("similarity: ", cosine)

similarity:  0.10050378152592121


In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc1 = nlp(u'Two children, a girl  reaching for the cookie jar.') 
doc2 = nlp(u'Mother is She has a dish in your hand or is.')
print (doc1.similarity(doc2)) 

0.4966613486251336


/usr/lib/python3.7/runpy.py:193: ModelsWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  "__main__", mod_spec)


In [ ]:
!pip install tensorflow
!pip install tensorflow_hub

In [ ]:
def heatmap(x_labels, y_labels, values):
    fig, ax = plt.subplots()
    im = ax.imshow(values)

    # We want to show all ticks...
    ax.set_xticks(np.arange(len(x_labels)))
    ax.set_yticks(np.arange(len(y_labels)))
    # ... and label them with the respective list entries
    ax.set_xticklabels(x_labels)
    ax.set_yticklabels(y_labels)

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right", fontsize=10,
         rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    for i in range(len(y_labels)):
        for j in range(len(x_labels)):
            text = ax.text(j, i, "%.2f"%values[i, j],
                           ha="center", va="center", color="w", 
fontsize=6)

    fig.tight_layout()
    plt.show()

In [ ]:
import tensorflow_hub as hub
import tensorflow as tf
import numpy as np
module_url = "https://tfhub.dev/google/universal-sentence-encoder/1?tf-hub-format=compressed"
# Import the Universal Sentence Encoder's TF Hub module
embed = hub.Module(module_url)

# sample text
messages = [
# Smartphones
"My phone is not good.",
"Your cellphone looks great.",

# Weather
"Will it snow tomorrow?",
"Recently a lot of hurricanes have hit the US",

# Food and health
"An apple a day, keeps the doctors away",
"Eating strawberries is healthy",
]

similarity_input_placeholder = tf.placeholder(tf.string, shape=(None))
similarity_message_encodings = embed(similarity_input_placeholder)
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    session.run(tf.tables_initializer())
    message_embeddings_ = session.run(similarity_message_encodings, feed_dict={similarity_input_placeholder: messages})

    corr = np.inner(message_embeddings_, message_embeddings_)
    print(corr)
    heatmap(messages, messages, corr)

In [ ]:
def heatmap(x_labels, y_labels, values):
    fig, ax = plt.subplots()
    im = ax.imshow(values)

    # We want to show all ticks...
    ax.set_xticks(np.arange(len(x_labels)))
    ax.set_yticks(np.arange(len(y_labels)))
    # ... and label them with the respective list entries
    ax.set_xticklabels(x_labels)
    ax.set_yticklabels(y_labels)

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right", fontsize=10,
         rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    for i in range(len(y_labels)):
        for j in range(len(x_labels)):
            text = ax.text(j, i, "%.2f"%values[i, j],
                           ha="center", va="center", color="w", 
fontsize=6)

    fig.tight_layout()
    plt.show()

## Word Embedding
Word Embedding, a technique in the language modeling domain, is utilized to map words or phrases that can be mapped to vectors of real numbers with several dimensions using word embedding. 
Different methods have been proposed as word embeddings. Here we review practices that have been used in the language of patients with dementia. 

1. Bag-Of-Words

2. Doc2vec 

3. Doc2vecC

4. TF-IDF

5. Word2Vec




### Bag-Of-Words

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
 
vector = CountVectorizer()
#
# Create sample set of documents
#
docs = np.array([
'Two children, a girl  reaching for the cookie jar. ',
'Mother is She has a dish in your hand or is.',
'They have a garden',
'There is a window with curtains', 
'The window was open. ',
'She is wearing a dress and apron. ',
'Cookie jar coverage open']
)
#
# Fit the bag-of-words model
#
bag = vector.fit_transform(docs)
#
# Get unique words / tokens found in all the documents. The unique words / tokens represents
# the features
#
print(vector.get_feature_names())
#
# Associate the indices with each unique word
#
print(vector.vocabulary_)
#
# Print the numerical feature vector
#
print(bag.toarray())

['and', 'apron', 'children', 'cookie', 'coverage', 'curtains', 'dish', 'dress', 'for', 'garden', 'girl', 'hand', 'has', 'have', 'in', 'is', 'jar', 'mother', 'open', 'or', 'reaching', 'she', 'the', 'there', 'they', 'two', 'was', 'wearing', 'window', 'with', 'your']
{'two': 25, 'children': 2, 'girl': 10, 'reaching': 20, 'for': 8, 'the': 22, 'cookie': 3, 'jar': 16, 'mother': 17, 'is': 15, 'she': 21, 'has': 12, 'dish': 6, 'in': 14, 'your': 30, 'hand': 11, 'or': 19, 'they': 24, 'have': 13, 'garden': 9, 'there': 23, 'window': 28, 'with': 29, 'curtains': 5, 'was': 26, 'open': 18, 'wearing': 27, 'dress': 7, 'and': 0, 'apron': 1, 'coverage': 4}
[[0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 2 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0]
 [1 1 0 0 0 0 0 1 0 0 0 0 0 0 0

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


### Doc2vec

In [ ]:
from gensim.test.utils import common_texts
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
common_texts = ['Two children, a girl  reaching for the cookie jar.']
#model = Doc2Vec(documents, vector_size=5, window=2, min_count=1, workers=4)
documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(common_texts)]
model = Doc2Vec(documents, vector_size=5, window=2, min_count=1, workers=4)

crawl-300d-2M-subword.zip: 2 million word vectors trained with subword information on Common Crawl (600B tokens).

### fastText
fastText is a python library for efficient learning of word representations [4].  

In [ ]:
! pip install fasttext

     |████████████████████████████████| 68 kB 2.8 MB/s 
  Using cached pybind11-2.9.0-py2.py3-none-any.whl (210 kB)
  Created wheel for fasttext: filename=fasttext-0.9.2-cp37-cp37m-linux_x86_64.whl size=3128379 sha256=254061b4f8d10038f7f41979c986052b67f780ceaca6b773baa945cadf5e0fb7
  Stored in directory: /root/.cache/pip/wheels/4e/ca/bf/b020d2be95f7641801a6597a29c8f4f19e38f9c02a345bab9b
Successfully built fasttext


In [9]:
import fasttext

In [11]:
import numpy as np
import fasttext as ft

In [15]:
txt = ['Two children, a girl  reaching for the cookie jar.']

In [ ]:
#model = fasttext.train_unsupervised(['Two children, a girl  reaching for the cookie jar.'], model='skipgram')


### Transformer-based Sentence Embeddings

As was mentioned embedding techniques such as word embeddings or sentence embeddings can be used as a technique to map words or a document to vectors of real numbers that could be used as aan input for machine learning methods. In [2], you can find a completed code to use BERT to map sentenses to vectors of real number. The focus of the following script is on generating sentence embeddings from patients'speech. 



In [ ]:
import torch

In [ ]:

S_1 = "Two children, a girl  reaching for the cookie jar."
S_2 = "Mother is She has a dish in your hand or is."  # this is very similar to 'g'
S_3 = "They have a garden"


In [ ]:
!pip install -qU transformers sentence-transformers

     |████████████████████████████████| 3.4 MB 5.0 MB/s 
     |████████████████████████████████| 78 kB 5.8 MB/s 
     |████████████████████████████████| 3.3 MB 40.7 MB/s 
     |████████████████████████████████| 895 kB 46.4 MB/s 
     |████████████████████████████████| 596 kB 45.5 MB/s 
     |████████████████████████████████| 61 kB 441 kB/s 
     |████████████████████████████████| 1.2 MB 47.7 MB/s 


In [ ]:
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/bert-base-nli-mean-tokens')
model = AutoModel.from_pretrained('sentence-transformers/bert-base-nli-mean-tokens')

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/418M [00:00<?, ?B/s]

In [ ]:
tokens = tokenizer([S_1, S_2, S_3],
                   max_length=128,
                   truncation=True,
                   padding='max_length',
                   return_tensors='pt')

In [ ]:
tokens.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [ ]:
tokens['input_ids'][0]

tensor([  101,  2048,  2336,  1010,  1037,  2611,  4285,  2005,  1996, 17387,
        15723,  1012,   102,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0])

In [ ]:
outputs = model(**tokens)
outputs.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [ ]:
embeddings = outputs.last_hidden_state
embeddings[0]

tensor([[-0.4413,  0.4672,  0.0789,  ...,  0.4469, -0.3015,  0.7256],
        [-0.5664,  0.2029, -0.0381,  ...,  0.2432, -0.2292,  0.4809],
        [-0.4949,  0.5591,  0.1316,  ..., -0.1351, -0.0885,  0.0900],
        ...,
        [-0.1514, -0.0262,  0.2503,  ...,  0.4395, -0.3653,  0.6493],
        [-0.3797,  0.2651,  0.1121,  ...,  0.4917, -0.5419,  0.4978],
        [-0.3267,  0.3079,  0.2471,  ...,  0.4822, -0.5646,  0.5483]],
       grad_fn=<SelectBackward0>)

In [ ]:
embeddings[0].shape

torch.Size([128, 768])


#### BioBert Embeddings: 
BioBERT embedding [3], a modified version of the BERT embedding, has been trained on PubMed articles and would be helpful for the languagr task in the biomedical domain. 

In [ ]:
!pip install biobert-embedding==0.1.2

     |████████████████████████████████| 748.9 MB 604 bytes/s 
     |████████████████████████████████| 123 kB 52.0 MB/s 
     |████████████████████████████████| 131 kB 49.3 MB/s 
     |████████████████████████████████| 8.5 MB 36.6 MB/s 
     |████████████████████████████████| 79 kB 6.7 MB/s 
     |████████████████████████████████| 138 kB 44.0 MB/s 
     |████████████████████████████████| 127 kB 51.6 MB/s 
  Created wheel for biobert-embedding: filename=biobert_embedding-0.1.2-py3-none-any.whl size=5701 sha256=4fed7f8b97c53e3c0b31e5f694aca59e67e5af45dd933cfa7eed7419e7de99d5
  Stored in directory: /root/.cache/pip/wheels/67/26/c2/176e174845e1612a5d607eea1d1876e2c9aca2b5654a5cd681
Successfully built biobert-embedding
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
  Attempting uninstall: torch
    Found existing installation: torch 1.10.0+cu111
    Uninstalling torch-1.10.0+cu111:

In [ ]:
from biobert_embedding.embedding import BiobertEmbedding

text = "Two children, a girl  reaching for the cookie jar. Mother is She has a dish in your hand or is."

# Class Initialization (You can set default 'model_path=None' as your finetuned BERT model path while Initialization)
biobert = BiobertEmbedding()

word_embeddings = biobert.word_vector(text)
sentence_embedding = biobert.sentence_vector(text)

print("Text Tokens: ", biobert.tokens)
# Text Tokens:  ['breast', 'cancers', 'with', 'her2', 'amplification', 'have', 'a', 'higher', 'risk', 'of', 'cns', 'metastasis', 'and', 'poorer', 'prognosis', '.']

print ('Shape of Word Embeddings: %d x %d' % (len(word_embeddings), len(word_embeddings[0])))
# Shape of Word Embeddings: 16 x 768

print("Shape of Sentence Embedding = ",len(sentence_embedding))
# Shape of Sentence Embedding =  768

Text Tokens:  ['two', 'children', ',', 'a', 'girl', 'reaching', 'for', 'the', 'cookie', 'jar', '.', 'mother', 'is', 'she', 'has', 'a', 'dish', 'in', 'your', 'hand', 'or', 'is', '.']
Shape of Word Embeddings: 23 x 768
Shape of Sentence Embedding =  768


## Tangentiality

## Grammatical error
To find out the grammatical errors in a text that a patient has provided with Alzheimer's disease dementia, you can use TextBlob Library
[TextBlob](https://pypi.org/project/textblob/0.9.0/), which is a text processing library. 

### Introduction to TextBlob


###*Installing TextBlob*

In [ ]:
!pip install textblob==0.9.0

In [ ]:
from textblob import TextBlob
text=TextBlob('I havv a bad spelling')
##For Spelling Correction, we can use correct() method to correct spell
#textc=text.correct()
#print(textc)
print(text)
print(text.correct())

I havv a bad spelling



## Introduction to Gingerit
Using gingerit,you can correcting spelling and grammar mistakes based on the context of complete entences.

### *Installing Gingerit*

In [ ]:
! pip install gingerit


     |████████████████████████████████| 63 kB 989 kB/s 
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.27.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.


In [ ]:
from gingerit.gingerit import GingerIt
import pandas as pd
text = "Two chldren, a grl reching for the cooki jar"
parser = GingerIt()
parser.parse(text)
b=parser.parse(text)
#pd.set_option('max_colwidth', 520)
corrected_df = parser.parse(text)
corrected_df = pd.DataFrame(corrected_df)
corrected_df

text  ...                                                                                                               corrections
0  Two chldren, a grl reching for the cooki jar  ...                {'start': 35, 'text': 'cooki', 'correct': 'cookie', 'definition': 'any of various small flat sweet cakes'}
1  Two chldren, a grl reching for the cooki jar  ...  {'start': 19, 'text': 'reching', 'correct': 'reaching', 'definition': 'the act of physically reaching or thrusting out'}
2  Two chldren, a grl reching for the cooki jar  ...                                            {'start': 15, 'text': 'grl', 'correct': 'girl', 'definition': 'a young woman'}
3  Two chldren, a grl reching for the cooki jar  ...                      {'start': 4, 'text': 'chldren', 'correct': 'children', 'definition': 'a young person of either sex'}

[4 rows x 3 columns]

# Refrences

[1]. [Overview of Text Similarity Metrics in Python](https://towardsdatascience.com/overview-of-text-similarity-metrics-3397c4601f50)

[2]. [BERT](https://colab.research.google.com/github/pinecone-io/examples/blob/master/semantic_search_intro/sbert.ipynb#scrollTo=KJuvX4-wp9Or)

[3]. [biobert-embedding 0.1.2]( https://pypi.org/project/biobert-embedding/) 

[4]. [fasttext 0.9.2](https://pypi.org/project/fasttext/)
